name: pyphylon-test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - biopython
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - plotly
  - umap-learn
  - hdbscan
  - selenium
  - webdriver-manager
  - pip
  - pip:
    - prince
    - kneebow
